if ($request_method = OPTIONS) {
    add_header 'Access-Control-Allow-Origin' $allowed_origins always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
    add_header 'Access-Control-Max-Age' 86400;
    return 204;
}
